name: 2020-10-21-sunburst
channels:
  - conda-forge
  - bioconda
  - defaults
  - plotly
dependencies:
  - snakemake-minimal=5.20.1
  - jupyterlab=2.2.8
  - notebook>=5.3
  - ipywidgets>=7.5
  - jupyterlab-plotly-extension
  - pandas=1.1.3
  - plotly=4.11.0
  - python-kaleido
